"""Frozen schema for 20260813 0001 land registry.

Revision ID: 20260813_0001
Revises: None
"""

from alembic import op
import sqlalchemy as sa

from migrations import migration_types


revision = "20260813_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'normalized_alias', name='uq_admin_alias_level')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('taluk', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('subdivision_number', sa.String(length=64), nullable=False),
    sa.Column('official_area_sqm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('geometry', migration_types.GeoJSONMultiPolygon(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('boundary_quality', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'district', 'taluk', 'village', 'survey_number', 'subdivision_number', name='uq_parcel_composite_key')
    )
    op.create_index('ix_parcel_lookup', 'parcels', ['state', 'district', 'taluk', 'village', 'survey_number', 'subdivision_number'], unique=False)
    op.create_index('parcels_geometry_gix', 'parcels', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    sa.UniqueConstraint('uploaded_by', 'idempotency_key', name='uq_document_idempotency')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claimant_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('claimed_area_sqm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('confirmed_fields_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('match_method', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claimant_id', 'idempotency_key', name='uq_claim_idempotency')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('structured_result_json', sa.JSON(), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('claim_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_a_id', sa.Uuid(), nullable=False),
    sa.Column('claim_b_id', sa.Uuid(), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('overlap_area_sqm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('overlap_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolution_history_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_a_id', 'claim_b_id', 'conflict_type', name='uq_conflict_pair_type')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("notifications")
    op.drop_table("audit_events")
    op.drop_table("claim_conflicts")
    op.drop_table("claims")
    op.drop_table("ocr_results")
    op.drop_table("documents")
    op.drop_table("administrative_aliases")
    op.drop_table("parcels")
    op.drop_table("users")
