"""Frozen schema for 20260902 0005 fra operational.

Revision ID: 20260902_0005
Revises: 20260826_0004
"""

from alembic import op
import sqlalchemy as sa

from migrations import migration_types


revision = "20260902_0005"
down_revision = '20260826_0004'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagery_scenes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=False),
    sa.Column('scene_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('footprint', migration_types.GeoJSONMultiPolygon(), nullable=False),
    sa.Column('cloud_cover', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('asset_references_json', sa.JSON(), nullable=False),
    sa.Column('license_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'collection', 'scene_id', name='uq_imagery_scene')
    )
    op.create_table('scheme_catalog_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('approving_authority', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('authoritative', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code', 'version', name='uq_scheme_catalog_version')
    )
    op.create_table('spatial_import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_kind', sa.String(length=64), nullable=False),
    sa.Column('source_authority', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('declared_crs', sa.String(length=100), nullable=True),
    sa.Column('detected_crs', sa.String(length=100), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('repaired_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('error_summary_json', sa.JSON(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_spatial_import_idempotency')
    )
    op.create_table('spatial_reference_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_kind', sa.String(length=64), nullable=False),
    sa.Column('source_authority', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('geometry', migration_types.GeoJSONMultiPolygon(), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['spatial_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_authority', 'source_version', 'source_record_id', name='uq_spatial_source_record')
    )
    op.create_table('dss_fact_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('derivation_version', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('facts_json', sa.JSON(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'derivation_version', 'idempotency_key', name='uq_dss_fact_snapshot')
    )
    op.create_table('fra_intake_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_claim_id', sa.Uuid(), nullable=False),
    sa.Column('promoted_claim_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('triage_json', sa.JSON(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legacy_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['promoted_claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_claim_id', name='uq_fra_intake_legacy_claim'),
    sa.UniqueConstraint('promoted_claim_id')
    )
    op.create_table('imagery_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('geometry_version_id', sa.Uuid(), nullable=False),
    sa.Column('imagery_scene_id', sa.Uuid(), nullable=True),
    sa.Column('processing_job_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('processor_version', sa.String(length=100), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('statistics_json', sa.JSON(), nullable=False),
    sa.Column('quality_flags_json', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['geometry_version_id'], ['fra_geometry_versions.id'], ),
    sa.ForeignKeyConstraint(['imagery_scene_id'], ['imagery_scenes.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'geometry_version_id', 'artifact_type', 'processor_version', name='uq_imagery_claim_geometry_artifact_processor')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("scheme_catalog_entries")
    op.drop_table("dss_fact_snapshots")
    op.drop_table("imagery_artifacts")
    op.drop_table("imagery_scenes")
    op.drop_table("spatial_reference_features")
    op.drop_table("spatial_import_batches")
    op.drop_table("fra_intake_items")
