"""Frozen schema for 20260826 0003 fra foundation.

Revision ID: 20260826_0003
Revises: 20260826_0002
"""

from alembic import op
import sqlalchemy as sa

from migrations import migration_types


revision = "20260826_0003"
down_revision = '20260826_0002'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gram_sabhas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('gram_panchayat', sa.String(length=255), nullable=True),
    sa.Column('block', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('boundary', migration_types.GeoJSONMultiPolygon(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_table('rights_holders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('holder_type', sa.String(length=32), nullable=False),
    sa.Column('claimant_category', sa.String(length=32), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('gram_sabha_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gram_sabha_id'], ['gram_sabhas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_table('scheme_rule_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('required_facts_json', sa.JSON(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_code', 'version', name='uq_scheme_rule_version')
    )
    op.create_table('fra_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('right_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rights_holder_id', sa.Uuid(), nullable=False),
    sa.Column('gram_sabha_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('legacy_claim_id', sa.Uuid(), nullable=True),
    sa.Column('parcel_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_area_sqm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['gram_sabha_id'], ['gram_sabhas.id'], ),
    sa.ForeignKeyConstraint(['legacy_claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.ForeignKeyConstraint(['rights_holder_id'], ['rights_holders.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number', name='uq_fra_claim_number'),
    sa.UniqueConstraint('legacy_claim_id', name='uq_fra_claim_legacy')
    )
    op.create_table('dss_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['scheme_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'rule_set_id', 'idempotency_key', name='uq_dss_actor_rule_idempotency')
    )
    op.create_table('fra_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('authority_level', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fra_geometry_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('geometry', migration_types.GeoJSONMultiPolygon(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('boundary_quality', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'version', name='uq_fra_geometry_claim_version')
    )
    op.create_table('fra_titles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=100), nullable=False),
    sa.Column('geometry_version_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['geometry_version_id'], ['fra_geometry_versions.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'version', name='uq_fra_title_claim_version'),
    sa.UniqueConstraint('title_number', name='uq_fra_title_number')
    )
    op.create_table('satellite_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('geometry_version_id', sa.Uuid(), nullable=True),
    sa.Column('scene_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=False),
    sa.Column('asset_class', sa.String(length=64), nullable=False),
    sa.Column('observed_value_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('analyser_version', sa.String(length=100), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['geometry_version_id'], ['fra_geometry_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'scene_id', 'claim_id', 'asset_class', name='uq_satellite_scene_claim_asset')
    )
    op.create_table('fra_evidence_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('legal_role', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('satellite_observation_id', sa.Uuid(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.Date(), nullable=True),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('source_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['satellite_observation_id'], ['satellite_observations.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_observation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("dss_recommendations")
    op.drop_table("scheme_rule_sets")
    op.drop_table("fra_titles")
    op.drop_table("fra_evidence_items")
    op.drop_table("satellite_observations")
    op.drop_table("fra_geometry_versions")
    op.drop_table("fra_decisions")
    op.drop_table("fra_claims")
    op.drop_table("rights_holders")
    op.drop_table("gram_sabhas")
