"""Frozen schema for 20260826 0004 fra completion.

Revision ID: 20260826_0004
Revises: 20260826_0003
"""

from alembic import op
import sqlalchemy as sa

from migrations import migration_types


revision = "20260826_0004"
down_revision = '20260826_0003'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fra_village_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('district_code', sa.String(length=64), nullable=False),
    sa.Column('district_name', sa.String(length=255), nullable=False),
    sa.Column('block_code', sa.String(length=64), nullable=False),
    sa.Column('block_name', sa.String(length=255), nullable=False),
    sa.Column('village_code', sa.String(length=64), nullable=False),
    sa.Column('village_name', sa.String(length=255), nullable=False),
    sa.Column('boundary', migration_types.GeoJSONMultiPolygon(), nullable=False),
    sa.Column('tribal_groups_json', sa.JSON(), nullable=False),
    sa.Column('socioeconomic_json', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('reference_version', sa.String(length=100), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code', 'district_code', 'block_code', 'village_code', name='uq_fra_village_natural_key')
    )
    op.create_table('fra_import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('error_summary_json', sa.JSON(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_fra_batch_idempotency')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('adapter_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('label_map_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'name', 'version', name='uq_model_task_name_version')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'entity_id', 'idempotency_key', name='uq_processing_job_idempotency')
    )
    op.create_table('inference_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('processing_job_id', sa.Uuid(), nullable=True),
    sa.Column('input_entity_type', sa.String(length=64), nullable=False),
    sa.Column('input_entity_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_report_idempotency')
    )
    op.create_table('asset_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('village_id', sa.Uuid(), nullable=True),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('asset_class', sa.String(length=64), nullable=False),
    sa.Column('polygon_geometry', migration_types.GeoJSONMultiPolygon(), nullable=True),
    sa.Column('point_geometry_json', sa.JSON(), nullable=True),
    sa.Column('observed_value_json', sa.JSON(), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('inference_run_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('verification_reasons_json', sa.JSON(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['inference_run_id'], ['inference_runs.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['asset_features.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['fra_village_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fra_archive_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('promoted_claim_id', sa.Uuid(), nullable=True),
    sa.Column('legacy_reference', sa.String(length=255), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=True),
    sa.Column('holder_display_name', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('block', sa.String(length=255), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('right_type', sa.String(length=16), nullable=True),
    sa.Column('claim_status', sa.String(length=32), nullable=True),
    sa.Column('claim_year', sa.Integer(), nullable=True),
    sa.Column('review_state', sa.String(length=32), nullable=False),
    sa.Column('reviewed_fields_json', sa.JSON(), nullable=False),
    sa.Column('duplicate_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['fra_import_batches.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['promoted_claim_id'], ['fra_claims.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'legacy_reference', name='uq_fra_archive_batch_legacy')
    )
    op.create_table('dss_referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('history_json', sa.JSON(), nullable=False),
    sa.Column('advisory_only', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['dss_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_dss_referral_idempotency'),
    sa.UniqueConstraint('recommendation_id', name='uq_dss_referral_recommendation')
    )
    op.create_table('fra_extraction_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('archive_record_id', sa.Uuid(), nullable=False),
    sa.Column('ocr_model_version_id', sa.Uuid(), nullable=True),
    sa.Column('entity_model_version_id', sa.Uuid(), nullable=True),
    sa.Column('ocr_model_version', sa.String(length=100), nullable=True),
    sa.Column('entity_model_version', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('standardized_json', sa.JSON(), nullable=False),
    sa.Column('field_evidence_json', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['archive_record_id'], ['fra_archive_records.id'], ),
    sa.ForeignKeyConstraint(['entity_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['ocr_model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("report_artifacts")
    op.drop_table("dss_referrals")
    op.drop_table("asset_features")
    op.drop_table("inference_runs")
    op.drop_table("fra_extraction_runs")
    op.drop_table("processing_jobs")
    op.drop_table("fra_archive_records")
    op.drop_table("fra_village_profiles")
    op.drop_table("model_versions")
    op.drop_table("fra_import_batches")
